#export AS := arm-none-eabi-as
export AS := arm-none-eabi-gcc -x assembler-with-cpp
export CC := arm-none-eabi-gcc
export LD := arm-none-eabi-ld
export OC := arm-none-eabi-objcopy

__GCC_OBJ = mkdir -p $(shell dirname $@); $(CC) $(CCFLAGS) $(DEFS) $(INCS) -c $< -o $@
__ASM_OBJ = $(AS) $(ASFLAGS) $(DEFS) -c $< -o $@
__LD_ELF  = $(LD) $^ $(LDFLAGS) -o $@
__OCP_BIN = $(OC) $(OBJCOPYFLAGS) $^ $@

#MAKE_VERBOSE = yes

ifeq ($(MAKE_VERBOSE),yes)
GCC_OBJ = $(__GCC_OBJ)
ASM_OBJ = $(__ASM_OBJ)
LD_ELF  = $(__LD_ELF) 
OCP_BIN = $(__OCP_BIN)
else
GCC_OBJ = @echo "  GCC       $@" ; $(__GCC_OBJ)
ASM_OBJ = @echo "  AS        $@" ; $(__ASM_OBJ)
LD_ELF  = @echo "  LD        $@" ; $(__LD_ELF) 
OCP_BIN = @echo "  OBJCOPY   $@" ; $(__OCP_BIN)
endif



